POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs )
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time background_jobs time )

typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique

typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='none'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=1

typeset -g POWERLEVEL9K_TIME_FORMAT='%H:%M'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3000
