local o = vim.opt
o.number = true
o.relativenumber = true
o.termguicolors = true
o.ignorecase = true
o.smartcase = true
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.cursorline = true
o.signcolumn = "yes"
o.updatetime = 300
o.splitright = true
o.splitbelow = true
